development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: letsmeetservices@gmail.com
  :password: LetsMeet!1234
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: letsmeetservices@gmail.com
  :password: LetsMeet!1234
  :enable_starttls_auto: true